# Controller generated by Typus, use it to extend admin functionality.
class Admin::OrdersController < Admin::MasterController
  def show
    order = Order.find(params[:id])
    redirect_to pnr_form_path(order.pnr_number)
  end
end
