Order:
  fields:
    default: pnr_number, email, phone, updated_at
    list:
      - source
      - pnr_number
      - blank_count
      - contact
      - created_at
      - price_with_payment_commission
      - payment_status
      - ticket_status
      - last_tkt_date
      - payment_type_decorated
      - has_refunds
      - partner
      - urgent
    show:
      - has_refunds
      - source
      - pnr_number
      - parent_pnr_number_searchable
      - offline_booking
      - description
      - route
      - payment_status
      - charged_on
      - ticket_status
      - contact_with_customer
      - name_in_card
      - pan
      - full_info
      - commission_ticketing_method
      - blank_count
      - price_fare
      - customized_original_price_fare
      - price_tax
      - customized_original_price_tax
      - commission_consolidator
      - price_consolidator
      - price_blanks
      - commission_discount
      - price_discount
      - commission_our_markup
      - price_our_markup
      - price_operational_fee
      - pricing_method
      - price_total
      - price_payment_commission
      - price_with_payment_commission
      - price_acquiring_compensation
      - fee
      - commission_agent
      - price_agent
      - commission_subagent
      - price_subagent
      - price_original
      - price_tax_extra
      - price_difference
      - fee_scheme
      - commission_carrier
      - commission_agent_comments
      - commission_subagent_comments
      - commission_designator
      - commission_tour_code
      - created_at
      - updated_at
      - last_tkt_date
      - payment_type_decorated
      - delivery
      - last_pay_time
      - partner
      - income_suppliers
      - aggregated_income_suppliers
      - income_payment_gateways
      - expected_income
      - balance
      - settled?
      - display_fee_details
      - auto_ticket
      - no_auto_ticket_reason
      - needs_visa_notification
    form:
      - section_general_info
      - description
      - has_refunds
      - email
      - phone
      - source
      - pnr_number
      - parent_pnr_number
      - sirena_lead_pass
      - route
      - payment_type
      - section_recalculation
      - recalculation_alert
      - commission_ticketing_method
      - blank_count
      - price_fare
      - price_tax
      - commission_agent
      - commission_subagent
      - commission_consolidator
      - price_consolidator
      - commission_blanks
      - commission_discount
      - commission_our_markup
      - price_operational_fee
      - pricing_method
      - price_acquiring_compensation
      - price_with_payment_commission
      - price_difference
      - commission_designator
      - commission_tour_code
      - fee_scheme
      - fix_price
      - section_state_and_control
      - ticket_status
      - offline_booking
      - last_pay_time
      - needs_update_from_gds
      - auto_ticket
    edit_ticketed:
      - section_general_info
      - description
      - has_refunds
      - email
      - phone
      - source
      - pnr_number
      - parent_pnr_number
      - sirena_lead_pass
      - route
      - payment_type
      - section_recalculation
      - recalculation_alert
      - commission_ticketing_method
      - blank_count
      - pricing_method
      - price_with_payment_commission
      - fee_scheme
      - fix_price
      - section_state_and_control
      - ticket_status
      - offline_booking
      - last_pay_time
      - needs_update_from_gds
    csv:
      - id
      - pnr_number
      - charged_on
      - created_date
      - ticketed_date
      - tickets_count
      - route
      - commission_carrier
      - price_fare
      - price_tax
      - price_consolidator
      - price_blanks
      - price_operational_fee
      - tickets_office_ids
      - price_agent
      - commission_agent
      - commission_subagent
      - commission_discount
      - price_subagent
      - price_discount
      - price_acquiring_compensation
      - price_with_payment_commission
      - price_difference
      - price_total
      - fee_scheme
      - expected_income
      - stored_balance
      - price_our_markup
      - income_payment_gateways
      - sold_tickets_numbers
      - refund_date
      - first_payment_ref
      - partner
    options:
      selectors: payment_type, source, ticket_status, pricing_method, commission_ticketing_method, fee_scheme
      booleans:
        has_refunds: ['да', 'нет']
        offline_booking: ['ручной', 'автоматический']
        old_booking: ["пересчет запрещен", "пересчет разрешен"]
      templates:
        needs_update_from_gds: boolean
        recalculation_alert: hint
        section_general_info: section
        section_recalculation: section
        section_state_and_control: section
      date_formats:
        created_at: long
        updated_at: long
        last_pay_time: long
        refund_date: long
  order_by: -orders.created_at
  search: ^pnr_number, ^parent_pnr_number, email, phone
  options:
    default_action_on_item: show
    export: csv
    #action_after_save: show
  actions:
    edit: show
  # тут не ввернешь конфирмации. временно убрал
  # actions:
  #   show: cancel, ticket, charge, unblock, show_pnr
  filters:  created_at, source, payment_status, ticket_status, payment_type, has_refunds, partner
  relationships: payments, tickets, order_comments, notifications
  application: Orders, 1
