Ticket:
  fields:
    default:
     - description
     - order
     - carrier
     - name
     - route
     - price_with_payment_commission
     - price_fare
     - price_tax
     - price_discount
     - price_our_markup
     - office_id
     - validator
     - status
     - kind
     - ticketed_date
     - itinerary_receipt
     - parent
     - confirm_refund_url
     - vat_included
    list:
      - link_to_show
      - order
      - carrier
      - name
      - route
      - price_fare
      - price_tax
      - price_refund
      - office_id
      - validator
      - status
      - kind
      - ticketed_date
      - itinerary_receipt
      - parent
      - processed
    new:  price_fare, price_tax, price_penalty, price_discount, price_our_markup, ticketed_date, comment
    show:
      - old_booking
      - order
      - carrier
      - number_with_code
      - last_name
      - first_name
      - route
      - price_fare
      - price_tax
      - commission_consolidator
      - price_consolidator
      - price_blanks
      - commission_agent
      - price_agent
      - commission_subagent
      - price_subagent
      - commission_discount
      - price_discount
      - commission_our_markup
      - price_our_markup
      - price_penalty
      - price_payment_commission
      - price_with_payment_commission
      - office_id
      - validator
      - commission_ticketing_method
      - status
      - ticketed_date
      - itinerary_receipt
      - mso_number
    edit:
      - code
      - number
      - status
      - ticketed_date
      - validating_carrier
      - last_name
      - first_name
      - route
      - price_fare
      - price_tax
      - commission_consolidator
      - commission_blanks
      - commission_agent
      - commission_subagent
      - commission_discount
      - commission_our_markup
      - price_penalty
      - office_id
      - validator
      - mso_number
      - comment
      - corrected_price
    new_refund: price_fare, price_tax, price_penalty, price_consolidator, price_discount, price_our_markup, route, comment
    confirm_refund: ticketed_date, processed
    csv:
      - source
      - number_with_code
      - ticket_date
      - carrier
      - route
      - cabins
      - price_fare
      - price_tax
      - price_total
      - price_consolidator
      - price_blanks
      - commission_agent
      - price_agent
      - commission_subagent
      - price_subagent
      - price_penalty
      - pnr_number
      - need_attention
      - validating_carrier
      - office_id
      - validator
      - status
      - ticketed_date
      - kind
      - mso_number
    options:
      selectors: status, source, office_id, validator
      date_formats:
        created_at: long
      booleans:
        processed: ["подтвержден", "не подтвержден"]
        old_booking: ["пересчет запрещен", "пересчет разрешен"]
        vat_included: ['да', 'нет']
  options:
    default_action_on_item: edit
  actions:
    edit: show
  order_by: -created_at
  filters: ticketed_date, source, validator, office_id, status
  relationships: order, other_tickets
  application: Orders, 1
  export: csv
  scopes: uncomplete
  search: ^number, last_name, first_name, ^pnr_number

