Ticket:
  fields:
    default:
     - description
     - order
     - carrier
     - name
     - route
     - price_with_payment_commission
     - price_fare
     - price_tax
     - price_penalty
     - price_discount
     - price_our_markup
     - price_operational_fee
     - office_id
     - validator
     - status
     - kind
     - ticketed_date
     - itinerary_receipt
     - parent
     - confirm_refund_url
     - vat_selector
    list:
      - link_to_show
      - order
      - carrier
      - name
      - route
      - price_fare
      - price_tax
      - office_id
      - validator
      - income_suppliers
      - status
      - kind
      - ticketed_date
      - dept_date
      - itinerary_receipt
      - parent
    new:
      - price_fare
      - price_tax
      - price_penalty
      - price_extra_penalty
      - price_operational_fee
      - price_acquiring_compensation
      - price_difference
      - ticketed_date
      - comment
      - code
      - number
      - status
      - validating_carrier
      - last_name
      - first_name
      - route
      - commission_consolidator
      - commission_blanks
      - commission_agent
      - commission_subagent
      - commission_discount
      - commission_our_markup
      - price_acquiring_compensation
      - office_id
      - validator
      - mso_number
    show:
      - old_booking
      - order
      - carrier
      - number_with_code
      - last_name
      - first_name
      - route
      - price_fare
      - price_tax
      - price_penalty
      - price_extra_penalty
      - price_operational_fee
      - commission_consolidator
      - price_consolidator
      - price_blanks
      - commission_agent
      - price_agent
      - commission_subagent
      - price_subagent
      - commission_discount
      - price_discount
      - commission_our_markup
      - price_our_markup
      - price_payment_commission
      - price_acquiring_compensation
      - price_difference
      - fee
      - price_with_payment_commission
      - office_id
      - validator
      - commission_ticketing_method
      - income_suppliers
      - status
      - ticketed_date
      - dept_date
      - itinerary_receipt
      - mso_number
      - display_fee_details
    edit:
      - code
      - number
      - status
      - ticketed_date
      - validating_carrier
      - last_name
      - first_name
      - route
      - price_fare
      - price_tax
      - price_penalty
      - price_extra_penalty
      - price_operational_fee
      - price_acquiring_compensation
      - price_difference
      - commission_consolidator
      - commission_blanks
      - commission_agent
      - commission_subagent
      - commission_discount
      - commission_our_markup
      - price_acquiring_compensation
      - office_id
      - validator
      - mso_number
      - comment
      - corrected_price
    new_refund: price_fare, price_tax, price_penalty, price_consolidator, price_discount, price_our_markup, price_extra_penalty, price_operational_fee, price_acquiring_compensation, route, comment
    confirm_refund: ticketed_date, status
    csv:
      - source
      - number_with_code
      - carrier
      - route
      - cabins
      - price_fare
      - price_tax
      - price_penalty
      - price_total
      - price_consolidator
      - price_discount
      - price_our_markup
      - price_blanks
      - price_operational_fee
      - commission_agent
      - price_agent
      - commission_subagent
      - commission_discount
      - price_subagent
      - price_with_payment_commission
      - price_acquiring_compensation
      - price_difference
      - pnr_number
      - validating_carrier
      - office_id
      - validator
      - income_suppliers
      - status
      - ticketed_date
      - dept_date
      - kind
      - mso_number
      - last_name
      - order.pricing_method
      - parent_number_with_code
      - replacement_number_with_code
      - vat_status
    options:
      selectors: status, source, office_id, validator
      date_formats:
        created_at: long
      booleans:
        old_booking: ["пересчет запрещен", "пересчет разрешен"]
  options:
    default_action_on_item: edit
    start_year: 2011
    end_year: <%= (Date.today + 1.month).year %>
    export: csv
  actions:
    edit: show
  order_by: -tickets.created_at
  filters: ticketed_date, dept_date, validating_carrier, source, validator, office_id, status, kind
  relationships: order, other_tickets
  application: Orders, 1
  scopes: uncomplete, sold
  search: ^number, last_name, first_name, ^pnr_number

