# put local overrides in config/local.yml or config/local/*.yml
amadeus:
  production:
    endpoint: "https://production.webservices.amadeus.com"
  endpoint: "https://test.webservices.amadeus.com"
payture:
  key: MerchantETerra
  host: engine-sandbox.payture.com
  ssl: false
  pem: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp6EhXtBS3uHS24D2F+jE
    wHga8Vj+UXkeXM9u4AjlePa/b+RCbD3l8C//HsCpNc9nEKbu65ilkhyRngPO0N0j
    j4/ULboDarA2QWrjz/LJf0NpyLBeBexQYYkZlMVcVQV3H5s8l8zQ8IPHeIw1BZ7U
    yDpcH//d/GbHUXQrzlF3AFIV+OJTCEoYgCgKxFie0c/VhmQVTrdvlvPABxwSEfZ5
    Gyd9QZs9udAEwMiKDzE9g9QkYD4rB88iwExAX0kXNZTv1k77Exx/ppGeY7E873OZ
    jEqhpDYkFUu0XMbGBYr0m6JcVXHGy3xV4J7YasVrvs0kqYJNiyaUhaHQYbAM2AWz
    IwIDAQAB
    -----END PUBLIC KEY-----
sirena:
  enabled: false
  host: delta.eviterra.com
  port: 8888
  path: /
geolocation:
  enabled: false
  production:
    enabled: true
