# put local overrides in config/local.yml or config/local/*.yml
api:
  enabled: yes
amadeus:
  endpoint: "https://test.webservices.amadeus.com"
  enabled: yes
  nonstop_search: yes
  calendar: yes
  fake: no
  recommendations_lite: 20
  euro_rate: 40
payment:
  skip_checksum_validation: yes
  order_id_prefix: o
  production:
    skip_checksum_validation: no
payture:
  enabled: yes
  key: MerchantETerra
  host: sandbox.payture.com
  ssl: no
  pem: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp6EhXtBS3uHS24D2F+jE
    wHga8Vj+UXkeXM9u4AjlePa/b+RCbD3l8C//HsCpNc9nEKbu65ilkhyRngPO0N0j
    j4/ULboDarA2QWrjz/LJf0NpyLBeBexQYYkZlMVcVQV3H5s8l8zQ8IPHeIw1BZ7U
    yDpcH//d/GbHUXQrzlF3AFIV+OJTCEoYgCgKxFie0c/VhmQVTrdvlvPABxwSEfZ5
    Gyd9QZs9udAEwMiKDzE9g9QkYD4rB88iwExAX0kXNZTv1k77Exx/ppGeY7E873OZ
    jEqhpDYkFUu0XMbGBYr0m6JcVXHGy3xV4J7YasVrvs0kqYJNiyaUhaHQYbAM2AWz
    IwIDAQAB
    -----END PUBLIC KEY-----
payonline:
  enabled: no
  merchant_id: '3925'
  private_security_key: '3495dbcb-aa90-46d4-91cf-8be89238ac77'
  host: secure.payonlinesystem.com
  preauthorization: true
cbr:
  usd:
    2011-01-01: 30.0000
    2011-01-02: 30.0001
sirena:
  enabled: no
  restrict: no
  fake: no
  timeout_lite: 20
  host: localhost
  port: 8888
  path: /
geolocation:
  enabled: no
  production:
    enabled: yes
mail:
  ticket_cc: ~

