# put local overrides in config/local.yml or config/local/*.yml
site:
  forbidden_booking: no
  forbidden_sale: no
  forbidden_cash: no
  forbidden_delivery: no
  store_flights: no
  host: 'http://localhost:3000'
  fee_scheme: v2
  production:
    host: 'https://eviterra.com'
  staging:
    host: 'https://staging.eviterra.com'
  test:
    host: 'http://localhost:3000'
api:
  enabled: yes
  store_rambler_cache: no
  url_base: 'https://eviterra.com'
  rambler_url: 'http://in.avia.rambler.ru/eviterra/'
  send_to_rambler: no
  rambler_hash_size: 30
  passwords: {}
  test:
    passwords:
      testpartner: testpass
amadeus:
  endpoint: "https://test.webservices.amadeus.com"
  enabled: yes
  nonstop_search: yes
  calendar: yes
  fake: no
  logging: no
  recommendations_lite: 20
  recommendations_full: 200
  euro_rate: 40
  session_pool_size: 10
  no_ltd_restrictions: no
  cancel_stale: no
  ignored_carriers: []
  forbid_class_changing: no
  default_office: MOWR228FA
  offices:
    MOWR228FA:
      alias: booking
      # alias: direct
      organization: NMC-RUSSIA
      password: MI8VX87M
    MOWR2233B:
      alias: ticketing
      # alias: aviacenter
      organization: NMC-RUSSIA
      password: MI8VX87M
    NYC1S21HX:
      alias: downtown
      organization: NMC-US
      password: MI8VX87M
    IEVU228GZ:
      alias: zagorye
      organization: NMC-UKRAIN
      password: AMADEUS
payment:
  skip_checksum_validation: yes
  # payture, payu, or no
  card_processing: payture
  # глобальная комиссия для некорпоратов
  # использую ее при корректировке цен
  commission: 2.85%
  test_multiplier: ~
  # стоимость доставки
  price_delivery: 400
  # дефолтное значение штрафа за возврат
  # писать хэшом вида
  # refund_fees:
  #   2013-02-12: 500
  #   2013-03-05: 200
  refund_fees: {}
  production:
    skip_checksum_validation: no
cash:
  commission: 2.85%
  corporate_commission: 0
payture:
  commission: 2.85%
  ref_prefix: o
  key: MerchantETerra
  host: sandbox.payture.com
  ssl: no
  pem: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp6EhXtBS3uHS24D2F+jE
    wHga8Vj+UXkeXM9u4AjlePa/b+RCbD3l8C//HsCpNc9nEKbu65ilkhyRngPO0N0j
    j4/ULboDarA2QWrjz/LJf0NpyLBeBexQYYkZlMVcVQV3H5s8l8zQ8IPHeIw1BZ7U
    yDpcH//d/GbHUXQrzlF3AFIV+OJTCEoYgCgKxFie0c/VhmQVTrdvlvPABxwSEfZ5
    Gyd9QZs9udAEwMiKDzE9g9QkYD4rB88iwExAX0kXNZTv1k77Exx/ppGeY7E873OZ
    jEqhpDYkFUu0XMbGBYr0m6JcVXHGy3xV4J7YasVrvs0kqYJNiyaUhaHQYbAM2AWz
    IwIDAQAB
    -----END PUBLIC KEY-----
payu:
  commission: 2.85%
  ref_prefix: payu_
  seller_key: 'w7I2R8~V7=dm5H7[r1k5'
  host: sandbox8ru.epayment.ro
  merchant: EVITERRA
payonline:
  enabled: no
  merchant_id: '3925'
  private_security_key: '3495dbcb-aa90-46d4-91cf-8be89238ac77'
  host: secure.payonlinesystem.com
  preauthorization: true
cbr:
  usd:
    2011-01-01: 30.0000
    2011-01-02: 30.0001
sirena:
  enabled: no
  enabled_in_lite: no
  restrict: no
  fake: no
  timeout_lite: 20
  timeout_full: 50
  host: localhost
  port: 8888
geolocation:
  enabled: no
  production:
    enabled: yes
mail:
  ticket_cc: ~
  subscription_reply_to: operator@eviterra.com
  subscription_cc: subscription@eviterra.com
  invoice_to: bills@eviterra.com
ohmystats:
  enabled: yes
  project_id: tyjrlhjuionhuxvojzbravinzfejcnsdgcoyjsks
  production:
    enabled: yes
    project_id: qsxfvashjzioiwazcryxlgysgjuitwyfaasjvkiv
riemann:
  enabled: yes
  host: riemann.eviterra.com
  benchmarking: no
  request_performance: no
  stat_counters: no
  test:
    host: localhost
  production:
    benchmarking: yes
    request_performance: yes