#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

require 'readline'
prompt = 'amadeus > '
begin
  office = ( ARGV.shift == 'ticketing' ?
    Amadeus::Session::TICKETING : Amadeus::Session::BOOKING
  )
  amadeus = Amadeus::Service.new(:book => true, :office => office)
  while !(command_line = Readline.readline(prompt, true)).nil?
    command_line.chomp!
    break if command_line == 'q'
    next if command_line == ''
    puts amadeus.cmd(command_line)
  end
ensure
  puts "logging out amadeus session ..."
  amadeus.session.destroy if amadeus
end
