#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

require 'readline'
prompt = ''

if ARGV.size > 0
  office = Amadeus.office(ARGV.shift)
else
  office = Conf.amadeus.default_office
end
prompt = "#{Conf.amadeus.env} #{office} > "

Amadeus.session(office) do |amadeus|
  while command_line = Readline.readline(prompt, true)
    command_line.chomp!
    break if command_line == 'q'
    next if command_line == ''
    command_line.split(';').each do |cmd|
      puts amadeus.cmd(cmd)
    end
  end
end
