#!/usr/bin/env ruby
# дамп базы без кэширующих и социально опасных таблиц
require 'optparse'
require 'yaml'

opts = {
}
setopt = proc {|key| proc {|value| opts[key] = value } }
OptionParser.new do |op|
  op.banner = "#{$0} [options] dumps database schema and data, skipping some contents."
  op.on "-t", "--trash", "Skip trash tables.", &setopt[:trash]
  op.on "-d", "--data", "Skip data tables.", &setopt[:data]
  op.on "-o", "--others", "Dump schemas for other tables.", &setopt[:others]
  op.on_tail("-h", "--help", "Show this message.") do
    puts op
    exit
  end
end.parse!

# FIXME просмотреть
ALL_TABLES = %W(
  airline_alliances
  airplanes
  airports
  amadeus_sessions
  carriers
  cities
  consolidators
  countries
  currency_rates
  customers
  destinations
  flight_groups
  geo_taggings
  geo_tags
  global_distribution_systems
  hot_offers
  imports
  imports_payments
  imports_tickets
  notifications
  order_comments
  orders
  orders_stored_flights
  partners
  payments
  promo_codes
  regions
  stored_flights
  stored_flights_tickets
  subscriptions
  tickets
  typus_users
  versions
)

GEO_TABLES = %W(
  countries
  cities
  airports
  regions
  carriers
  airplanes
)

TRASH_TABLES = %W(
  amadeus_sessions
  versions

  subscriptions
  notifications
  hot_offers
  destinations
  imports
  imports_payments
  imports_tickets

  order_comments
)

DATA_TABLES = %W(
  customers
  orders
  payments
  tickets

  stored_flights
  stored_flights_tickets
  orders_stored_flights
)

skip_tables = []
skip_tables += TRASH_TABLES if opts[:trash]
skip_tables += DATA_TABLES if opts[:data]

database_yml = YAML.load_file(File.expand_path('../../config/database.yml', __FILE__))
cfg = database_yml[ENV['RAILS_ENV'] || 'development' ]

cmd_pass = 'mysqldump'

cmd_pass += " -h #{cfg['host']}" if cfg['host']
cmd_pass += " -u #{cfg['username']}" if cfg['username']
cmd_pass += " -p#{cfg['password']}" if cfg['password']

# дампит схему и данные для неигнорируемых таблиц
ignore_tables_cmd = skip_tables.map { |t| "--ignore-table=#{cfg['database']}.#{t}"}.join(' ')
system "#{cmd_pass} #{cfg['database']} #{ignore_tables_cmd}"

if opts[:others]
  # дампит только схему для игнорируемых таблиц
  only_tables_cmd = skip_tables.join(' ') + ' --no-data'
  system "#{cmd_pass} #{cfg['database']} #{only_tables_cmd}"
end
