#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

include Amadeus::Fixtures
dir = ARGV.first || fail("usage: #{$0} dir/with/xml/responses")
rec = Recommendation.example('mowpar parmow')
Dir[dir + '/**/*'].each do |f|
  next unless File.file?(f)
  begin
    resp = amadeus_response(f)
    unless resp.success?
      puts [f, resp.error_message].join(' ')
      next
    end
    recs = resp.recommendations(rec)
    #puts f if recs.size > 1
    puts ([f] + recs.map {|r| [r.price_fare, r.price_tax].join('+')}).join(' ')
  rescue
    puts f
    raise
  end
end
