#!/usr/bin/env ruby

require 'optparse'

# defaults
$opts = {
  in: "config/commissions"
}

def setopt(attr)
  proc {|value| $opts[attr] = value}
end

OptionParser.new do |opts|
  opts.banner = "#{$0} [options] reads and dumps again commissions"
  opts.on "-i", "--in FILENAME", "commission file to read (config/commissions.rb by default)", &setopt(:in)
  opts.on "-o", "--out FILENAME", "commission file to write (STDOUT by default)", &setopt(:out)
  opts.on "-d", "--dir DIRNAME", "write commissions to directory", &setopt(:dir)
  opts.on "-y", "--yaml", "write in YAML format", &setopt(:yaml)
  opts.on "-s", "--discounts FILENAME", "apply discounts from file", &setopt(:discounts)
  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

# loading
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

unless $opts[:out]
  puts "working..."
end

book = Commission::Reader.new.read_file($opts[:in])

# выгружает текущие комиссии в yaml. для массового сравнения.

# чтобы убрать адреса и мусор, для сравнения после апдейта:
#   perl -lpe 's/[&*]\d+//' | grep -v 'source' > commissions.yml

if $opts[:out]
  outfh = File.open('w', outfile)
else
  outfh = STDOUT
end

if $opts[:discounts]
  puts "applying discounts..."
  discounts_file = File.open($opts[:discounts])
  discounts = discounts_file.readlines.map(&:chomp)
  discounts = discounts.map do |d|
    carrier, number, fx = d.split
    number = number.sub('#','').to_i
    fx = Commission::Formula.new(fx.sub(',', '.'))
    raise fx unless fx.valid?
    [carrier, number, fx]
  end

  discounts.each do |carrier, number, discount|
    page = book.find_page(carrier: carrier)
    rule = page.rules.find {|r| r.number == number } if page
    raise "no rule found for '#{carrier} ##{number}'" unless rule
    #puts "changing #{rule.discount} to #{discount}"
    rule.discount = discount
  end
end

if $opts[:yaml]
  # патчим to_yaml, чтобы атрибуты объектов сортировались
  class Psych::Visitors::YAMLTree
    def dump_ivars target
       ivars = find_ivars target

       ivars.sort_by(&:to_s).each do |iv|
         @emitter.scalar("#{iv.to_s.sub(/^@/, '')}", nil, nil, true, false, Psych::Nodes::Scalar::ANY)
         accept target.instance_variable_get(iv)
       end
    end
  end

  outfh << book.to_yaml
else
  if $opts[:dir]
    puts "writing commissions to dir #{$opts[:dir]}"
    Commission::Writer::Book.new(book).write_dir($opts[:dir])
  else
    outfh << Commission::Writer::Book.new(book).write
  end
end
