#!/usr/bin/env ruby
# дамп базы - только геотаблицы.
# TODO - объединить с dbdump

ONLY_TABLES = %W(
  countries
  cities
  airports
  regions
  carriers
  airplanes
)

require 'yaml'

database_yml = YAML.load_file(File.expand_path('../../config/database.yml', __FILE__))
cfg = database_yml[ENV['RAILS_ENV'] || 'development' ]

cmd_pass = 'mysqldump'

cmd_pass += " -h #{cfg['host']}" if cfg['host']
cmd_pass += " -u #{cfg['username']}" if cfg['username']
cmd_pass += " -p#{cfg['password']}" if cfg['password']

only_tables_cmd = ONLY_TABLES.join(' ')
system "#{cmd_pass} #{cfg['database']} #{only_tables_cmd}"
