#!/usr/bin/env ruby
require_relative '../config/environment'
require 'yajl'

Dir.chdir(Rails.root)

Daemons.run_proc('/tmp/pids/rambler_daemon') do
  if Conf.api.send_to_rambler
    logger = ActiveSupport::BufferedLogger.new(Rails.root + 'log/rambler.log')
    db = Mongoid.default_session
    coll = db.collection('rambler_caches')
    cursor = Mongo::Cursor.new(coll, :tailable => true)
    data_to_send = []
    loop do
      begin
        doc = cursor.next_document
      rescue Mongo::OperationFailure
        logger.error "Mongo::OperationFailure"
        cursor = Mongo::Cursor.new(coll, :tailable => true)
        retry
      end
      if doc
        data_to_send << {:request => doc['pricer_form_hash'], :variants => doc['data']}
        if data_to_send.size >= Conf.api.rambler_hash_size
          json_string = Yajl::Encoder.encode(data_to_send)
          begin
            response = HTTParty.post(Conf.api.rambler_url, :body => json_string, :format => :json)
            logger.info "Rambler api: request with #{data_to_send.count} searches sent"
          rescue Exception => e
            logger.error "Problem sending rambler hash: #{e.message}"
          end
          data_to_send = []
        end
      else
        sleep 1
        logger.info 'Nothing to send'
      end
    end
  end
end
