#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

factories!
order = OrderForm.load_from_cache('50225c0364047a0aee00003e')
order.recommendation.find_commission!
order.email = 'email@example.com'
order.phone = '12345678'
#order.people_count = {:infants => 1, :children => 1, :adults => 2}
order.people = [FactoryGirl.build(:person,
  :first_name => 'ALEXANDERA',
  :last_name => 'ROMANOVAKRYZHANOVSKAYA',
  :document_expiration => Date.today + 1.year,
  :passport => '999999343',
  :nationality_code => 'RUS',
  :sex => 'f',
  :bonus_present => true,
  :bonuscard_type => 'SU',
  :bonuscard_number => '3456433'
),
FactoryGirl.build(:person,
  :last_name => 'Adult',
  :document_expiration => Date.today + 1.year,
  :passport => '999999999',
  :nationality_code => 'RUS',
  :sex => 'm',
),
FactoryGirl.build(:person, :infant,
  :last_name => 'Infant',
  :document_expiration => Date.today + 1.year,
  :passport => '88888888',
  :nationality_code => 'RUS',
  :sex => 'f'
)#,
=begin
FactoryGirl.build(:person, :child,
  :last_name => 'Child',
  :document_expiration => Date.today + 1.year,
  :passport => '77777777',
  :nationality_code => 'RUS',
  :sex => 'f'
)
=end
]
order.card = Payture.test_card
order.valid?
strategy = Strategy.select( :rec => order.recommendation, :order_form => order )
booking_status = strategy.create_booking
puts booking_status
puts order.order.pnr_number
puts strategy.raw_pnr

#Amadeus.booking do |amadeus|
#  resp = amadeus.pnr_retrieve(:number => order.order.pnr_number)
#  puts resp.doc.to_xml
#end
strategy.cancel
