#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

order = OrderForm.load_from_cache('4fd8aeb564047a0b08000018')
order.email = 'email@example.com'
order.phone = '12345678'
#order.people_count = {:infants => 1, :children => 1, :adults => 2}
order.people = [Person.new(
  :first_name => 'Anna',
  :last_name => 'Adult',
  :birthday => Date.today - 19.years,
  :document_expiration_date => Date.today + 1.year,
  :passport => '999999343',
  :nationality_id => 1,
  :sex => 'f',
  :bonus_present => false,
  :bonus_present => true,
  :bonuscard_type => 'SU',
  :bonuscard_number => '3456433'
),
  Person.new(
  :first_name => 'Ivan',
  :last_name => 'Adult',
  :birthday => Date.today - 20.years,
  :document_expiration_date => Date.today + 1.year,
  :passport => '999999999',
  :nationality_id => 1,
  :sex => 'm',
),
Person.new(
  :first_name => 'Masha',
  :last_name => 'Infant',
  :birthday => Date.today - 1.years,
  :document_expiration_date => Date.today + 1.year,
  :passport => '88888888',
  :nationality_id => 1,
  :sex => 'f'
),
Person.new(
  :first_name => 'Masha',
  :last_name => 'Child',
  :birthday => Date.today - 10.years,
  :document_expiration_date => Date.today + 1.year,
  :passport => '77777777',
  :nationality_id => 1,
  :sex => 'f'
)]
order.card = Payture.test_card
order.valid?
strategy = Strategy.select( :rec => order.recommendation, :order_form => order )
booking_status = strategy.create_booking
puts booking_status
puts order.order.pnr_number
puts strategy.raw_pnr

#Amadeus.booking do |amadeus|
#  resp = amadeus.pnr_retrieve(:number => order.order.pnr_number)
#  puts resp.doc.to_xml
#end
strategy.cancel
