City.create({:iata=>"CEJ", :iata_ru=>"ЧГВ", :name_en=>"Chernigov", :name_ru=>"Чернигов", :country_id=>215, :timezone=>"Etc/GMT+2", :sirena_name=>"original", :morpher_to=>"в Чернигов", :morpher_from=>"из Чернигова", :morpher_in=>"в Чернигове", :lat=>31.2984, :lng=>51.491108})
City.create({:iata=>"AMV", :iata_ru=>"АМД", :name_en=>"Amderma", :name_ru=>"Амдерма", :country_id=>170, :timezone=>"Etc/GMT+4", :sirena_name=>"original", :morpher_to=>"в Амдерму", :morpher_from=>"из Амдермы", :morpher_in=>"в Амдерме", :lat=>61.673881, :lng=>69.758802})
City.create({:iata=>"NSK", :iata_ru=>"НРС", :name_en=>"Norilsk", :name_ru=>"Норильск", :country_id=>170, :timezone=>"Etc/GMT+7", :sirena_name=>"original", :morpher_to=>"в Норильск", :morpher_from=>"из Норильска", :morpher_in=>"в Норильске", :lat=>88.220481, :lng=>69.330406})
City.create({:iata=>"УЧК", :iata_ru=>"УЧК", :name_en=>"Красноярск Учебный", :name_ru=>"Красноярск Учебный", :country_id=>170, :timezone=>"Etc/GMT+7", :sirena_name=>"original", :morpher_to=>"в Красноярск Учебный", :morpher_from=>"из Красноярск Учебного", :morpher_in=>"в Красноярск Учебного", :lat=>95.692982, :lng=>56.219552})
City.create({:iata=>"ULY", :iata_ru=>"УЛК", :name_en=>"Ulyanovsk", :name_ru=>"Ульяновск", :country_id=>170, :timezone=>"Etc/GMT+4", :sirena_name=>"original", :morpher_to=>"в Ульяновск", :morpher_from=>"из Ульяновска", :morpher_in=>"в Ульяновске", :lat=>48.472015, :lng=>54.316581})
City.create({:iata=>"KUT", :iata_ru=>"КИС", :name_en=>"Kutaisi", :name_ru=>"Кутаиси", :country_id=>58, :timezone=>"Etc/GMT+4", :sirena_name=>"original", :morpher_to=>"в Кутаиси", :morpher_from=>"из Кутаиси", :morpher_in=>"в Кутаиси", :lat=>42.692434, :lng=>42.233128})
City.create({:iata=>"МКП", :iata_ru=>"МКП", :name_en=>"Maykop", :name_ru=>"Майкоп", :country_id=>170, :timezone=>"Etc/GMT+3", :sirena_name=>"original", :morpher_to=>"в Майкоп", :morpher_from=>"из Майкопа", :morpher_in=>"в Майкопе", :lat=>40.102348, :lng=>44.609539})
City.create({:iata=>"ТАУ", :iata_ru=>"ТАУ", :name_en=>"Tura", :name_ru=>"Тура Горный", :country_id=>170, :timezone=>"Etc/GMT+7", :sirena_name=>"original", :morpher_to=>"в Тура Горный", :morpher_from=>"из Тура Горного", :morpher_in=>"в Тура Горного", :lat=>52.42939, :lng=>57.679016})
City.create({:iata=>"KAY", :iata_ru=>"КАЫ", :name_en=>"Karym", :name_ru=>"Карым", :country_id=>170, :timezone=>"Etc/GMT+5", :sirena_name=>"original", :morpher_to=>"в Карым", :morpher_from=>"из Карыма", :morpher_in=>"в Карыме", :lat=>66.610087, :lng=>60.077638})
City["MSQ"].update_attributes({:iata_ru=>"МСК"})
City["OMS"].update_attributes({:iata_ru=>"ОМС"})
City["IAR"].update_attributes({:iata_ru=>"ЯРЛ"})
City["KHV"].update_attributes({:iata_ru=>"ХБР"})
City["MOW"].update_attributes({:iata_ru=>"МОВ"})
City["LED"].update_attributes({:iata_ru=>"СПТ"})
City["LON"].update_attributes({:iata_ru=>"LON"})
City["STO"].update_attributes({:iata_ru=>"STO"})
City["BER"].update_attributes({:iata_ru=>"БРЛ"})
City["CHI"].update_attributes({:iata_ru=>"CHI"})
City["IEV"].update_attributes({:iata_ru=>"ИЕВ"})
City["OVB"].update_attributes({:iata_ru=>"ОВБ"})
City["DYR"].update_attributes({:iata_ru=>"АНЫ"})
City["PKC"].update_attributes({:iata_ru=>"ПРЛ", :sirena_name=>"Петропавловск Камчатский"})
City["BAK"].update_attributes({:iata_ru=>"БАК"})
City["ALA"].update_attributes({:iata_ru=>"АЛА", :sirena_name=>"Алма Ата"})
City["AAQ"].update_attributes({:iata_ru=>"АНА"})
City["ARH"].update_attributes({:iata_ru=>"АРХ"})
City["NYC"].update_attributes({:iata_ru=>"NYC", :sirena_name=>"Нью Йорк"})
City["VIN"].update_attributes({:iata_ru=>"ВИН"})
City["PEE"].update_attributes({:iata_ru=>"ПРМ"})
City["PES"].update_attributes({:iata_ru=>"ПТЗ"})
City["ODS"].update_attributes({:iata_ru=>"ОДС"})
City["BTK"].update_attributes({:iata_ru=>"БРС"})
City["KZN"].update_attributes({:iata_ru=>"КЗН"})
City["DNK"].update_attributes({:iata_ru=>"ДПК"})
City["EVN"].update_attributes({:iata_ru=>"ЕВН"})
City["SVX"].update_attributes({:iata_ru=>"ЕКБ"})
City["KJA"].update_attributes({:iata_ru=>"КЯА"})
City["KRR"].update_attributes({:iata_ru=>"КРР"})
City["KUF"].update_attributes({:iata_ru=>"СМШ"})
City["GDX"].update_attributes({:iata_ru=>"МДН"})
City["TJM"].update_attributes({:iata_ru=>"ТЮМ"})
City["TAS"].update_attributes({:iata_ru=>"ТАС"})
City["SIP"].update_attributes({:iata_ru=>"СИП"})
City["FRA"].update_attributes({:iata_ru=>"ФРА", :sirena_name=>"Франкфурт На Майне"})
City["MUC"].update_attributes({:iata_ru=>"МЮН"})
City["UFA"].update_attributes({:iata_ru=>"УФА"})
City["MIL"].update_attributes({:iata_ru=>"МИА"})
City["PAR"].update_attributes({:iata_ru=>"ПАЖ"})
City["VCE"].update_attributes({:iata_ru=>"ВЕЦ"})

Airport.create({:iata=>"ОМЬ", :iata_ru=>"ОМЬ", :name_en=>"Omsk Mvl", :name_ru=>"Омск Мвл", :city_id=>2128, :sirena_name=>"original", :morpher_to=>"в Омск Мвл", :morpher_from=>"из Омск Мвла", :morpher_in=>"в Омск Мвле", :lat=>73.365364, :lng=>54.990302})
Airport.create({:iata=>"ЧНШ", :iata_ru=>"ЧНШ", :name_en=>"Шестовица", :name_ru=>"Шестовица", :city_id=>3619, :sirena_name=>"original", :morpher_to=>"в Шестовицу", :morpher_from=>"из Шестовицы", :morpher_in=>"в Шестовице", :lat=>31.2984, :lng=>51.491108})
Airport.create({:iata=>"ЧГВ", :iata_ru=>"ЧГВ", :name_en=>"Чернигов", :name_ru=>"Чернигов", :city_id=>3619, :sirena_name=>"original", :morpher_to=>"в Чернигов", :morpher_from=>"из Чернигова", :morpher_in=>"в Чернигове", :lat=>31.2984, :lng=>51.491108})
Airport.create({:iata=>"ЯРВ", :iata_ru=>"ЯРВ", :name_en=>"Левцово", :name_ru=>"Левцово", :city_id=>3611, :sirena_name=>"original", :morpher_to=>"в Левцово", :morpher_from=>"из Левцово", :morpher_in=>"в Левцово", :lat=>40.041874, :lng=>57.735737})
Airport.create({:iata=>"ЯРТ", :iata_ru=>"ЯРТ", :name_en=>"Туношна", :name_ru=>"Туношна", :city_id=>3611, :sirena_name=>"original", :morpher_to=>"в Туношну", :morpher_from=>"из Туношны", :morpher_in=>"в Туношне", :lat=>40.121779, :lng=>57.541903})
Airport.create({:iata=>"KHA", :iata_ru=>"ХБА", :name_en=>"Xabarovsc2", :name_ru=>"Хабаровск2", :city_id=>3249, :sirena_name=>"original", :morpher_to=>"в Хабаровск2", :morpher_from=>"из Хабаровск2а", :morpher_in=>"в Хабаровск2е", :lat=>135.056475, :lng=>48.460732})
Airport.create({:iata=>"BKA", :iata_ru=>"БКВ", :name_en=>"Bykovo", :name_ru=>"Быково", :city_id=>1899, :sirena_name=>"original", :morpher_to=>"в Быково", :morpher_from=>"из Быково", :morpher_in=>"в Быково", :lat=>37.974266, :lng=>55.566481})
Airport.create({:iata=>"РНЦ", :iata_ru=>"РНЦ", :name_en=>"Раменское", :name_ru=>"Раменское", :city_id=>1899, :sirena_name=>"original", :morpher_to=>"в Раменское", :morpher_from=>"из Раменское", :morpher_in=>"в Раменское", :lat=>38.226962, :lng=>55.574258})
Airport.create({:iata=>"ЧКЛ", :iata_ru=>"ЧКЛ", :name_en=>"Чкаловск", :name_ru=>"Чкаловск", :city_id=>1899, :sirena_name=>"original", :morpher_to=>"в Чкаловск", :morpher_from=>"из Чкаловска", :morpher_in=>"в Чкаловске", :lat=>37.609218, :lng=>55.753559})
Airport.create({:iata=>"ПШН", :iata_ru=>"ПШН", :name_en=>"Puhcin", :name_ru=>"Пушкин", :city_id=>2600, :sirena_name=>"original", :morpher_to=>"в Пушкин", :morpher_from=>"из Пушкина", :morpher_in=>"в Пушкине", :lat=>30.398405, :lng=>59.717277})
Airport.create({:iata=>"RVH", :iata_ru=>"РЖВ", :name_en=>"Rjevka", :name_ru=>"Ржевка", :city_id=>2600, :sirena_name=>"original", :morpher_to=>"в Ржевку", :morpher_from=>"из Ржевкы", :morpher_in=>"в Ржевке", :lat=>30.505278, :lng=>59.977093})
Airport.create({:iata=>"ВКЬ", :iata_ru=>"ВКЬ", :name_en=>"Vasilcov", :name_ru=>"Васильков", :city_id=>1189, :sirena_name=>"original", :morpher_to=>"во Васильков", :morpher_from=>"из Василькова", :morpher_in=>"во Василькове", :lat=>30.33396, :lng=>50.187299})
Airport.create({:iata=>"НВЦ", :iata_ru=>"НВЦ", :name_en=>"Ельцовка", :name_ru=>"Ельцовка", :city_id=>2012, :sirena_name=>"original", :morpher_to=>"в Ельцовку", :morpher_from=>"из Ельцовкы", :morpher_in=>"в Ельцовке", :lat=>82.821929, :lng=>55.063803})
Airport.create({:iata=>"СВР", :iata_ru=>"СВР", :name_en=>"Novosibirsk North", :name_ru=>"Новосибирск Северный", :city_id=>2012, :sirena_name=>"original", :morpher_to=>"в Новосибирск Северный", :morpher_from=>"из Новосибирск Северного", :morpher_in=>"в Новосибирск Северного", :lat=>82.919388, :lng=>55.029838})
Airport.create({:iata=>"ОЖН", :iata_ru=>"ОЖН", :name_en=>"Ocrujnoi", :name_ru=>"Окружной", :city_id=>101, :sirena_name=>"original", :morpher_to=>"в Окружной", :morpher_from=>"из Окружноя", :morpher_in=>"в Окружное", :lat=>177.477366, :lng=>64.736655})
Airport.create({:iata=>"ЗБР", :iata_ru=>"ЗБР", :name_en=>"Zabrat", :name_ru=>"Забрат", :city_id=>208, :sirena_name=>"original", :morpher_to=>"в Забрат", :morpher_from=>"из Забрата", :morpher_in=>"в Забрате", :lat=>49.977852, :lng=>40.420103})
Airport.create({:iata=>"БРУ", :iata_ru=>"БРУ", :name_en=>"Byryndaja", :name_ru=>"Бурундай", :city_id=>65, :sirena_name=>"original", :morpher_to=>"в Бурундай", :morpher_from=>"из Бурундая", :morpher_in=>"в Бурундае", :lat=>76.912335, :lng=>43.28081})
Airport.create({:iata=>"AMV", :iata_ru=>"АМД", :name_en=>"Амдерма", :name_ru=>"Амдерма", :city_id=>3620, :sirena_name=>"original", :morpher_to=>"в Амдерму", :morpher_from=>"из Амдермы", :morpher_in=>"в Амдерме", :lat=>61.673881, :lng=>69.758802})
Airport.create({:iata=>"АДЕ", :iata_ru=>"АДЕ", :name_en=>"Amderma2", :name_ru=>"Амдерма2", :city_id=>3620, :sirena_name=>"original", :morpher_to=>"в Амдерма2", :morpher_from=>"из Амдерма2а", :morpher_in=>"в Амдерма2е", :lat=>61.673881, :lng=>69.758802})
Airport.create({:iata=>"АМ1", :iata_ru=>"АМ1", :name_en=>"Amderma1", :name_ru=>"Амдерма1", :city_id=>3620, :sirena_name=>"original", :morpher_to=>"в Амдерма1", :morpher_from=>"из Амдерма1а", :morpher_in=>"в Амдерма1е", :lat=>61.673881, :lng=>69.758802})
Airport.create({:iata=>"АНА", :iata_ru=>"АНА", :name_en=>"Анапа", :name_ru=>"Анапа", :city_id=>104, :sirena_name=>"original", :morpher_to=>"в Анапу", :morpher_from=>"из Анапы", :morpher_in=>"в Анапе", :lat=>37.323087, :lng=>44.889844})
Airport.create({:iata=>"ВСЬ", :iata_ru=>"ВСЬ", :name_en=>"Vasikovo", :name_ru=>"Васьково", :city_id=>159, :sirena_name=>"original", :morpher_to=>"во Васьково", :morpher_from=>"из Васьково", :morpher_in=>"во Васьково", :lat=>40.457407, :lng=>64.410455})
Airport.create({:iata=>"АХГ", :iata_ru=>"АХГ", :name_en=>"Talagi", :name_ru=>"Архангельск Талаги", :city_id=>159, :sirena_name=>"original", :morpher_to=>"в Архангельск Талаги", :morpher_from=>"из Архангельск Талаги", :morpher_in=>"в Архангельск Талаги", :lat=>40.551776, :lng=>64.545818})
Airport.create({:iata=>"VGR", :iata_ru=>"ВГР", :name_en=>"Gavrishov", :name_ru=>"Гавришов", :city_id=>584, :sirena_name=>"original", :morpher_to=>"в Гавришов", :morpher_from=>"из Гавришова", :morpher_in=>"в Гавришове", :lat=>28.473702, :lng=>49.233571})
Airport.create({:iata=>"ПМЬ", :iata_ru=>"ПМЬ", :name_en=>"Baxarevc", :name_ru=>"Бахаревк", :city_id=>2250, :sirena_name=>"original", :morpher_to=>"в Бахаревк", :morpher_from=>"из Бахаревка", :morpher_in=>"в Бахаревке", :lat=>56.241077, :lng=>58.00849})
Airport.create({:iata=>"ПРЬ", :iata_ru=>"ПРЬ", :name_en=>"Perm Big Savino", :name_ru=>"Пермь Большое Савино", :city_id=>2250, :sirena_name=>"original", :morpher_to=>"в Пермь Большое Савино", :morpher_from=>"из Пермь Большое Савино", :morpher_in=>"в Пермь Большое Савино", :lat=>56.241077, :lng=>58.00849})
Airport.create({:iata=>"ПТД", :iata_ru=>"ПТД", :name_en=>"Pesci", :name_ru=>"Петрозаводск Пески", :city_id=>2259, :sirena_name=>"original", :morpher_to=>"в Петрозаводск Пески", :morpher_from=>"из Петрозаводск Пески", :morpher_in=>"в Петрозаводск Пески", :lat=>34.364692, :lng=>61.787569})
Airport.create({:iata=>"ПТБ", :iata_ru=>"ПТБ", :name_en=>"Besovets", :name_ru=>"Петрозаводск Бесовец", :city_id=>2259, :sirena_name=>"original", :morpher_to=>"в Петрозаводск Бесовец", :morpher_from=>"из Петрозаводск Бесовеца", :morpher_in=>"в Петрозаводск Бесовеце", :lat=>34.364692, :lng=>61.787569})
Airport.create({:iata=>"ВЛЕ", :iata_ru=>"ВЛЕ", :name_en=>"Valec", :name_ru=>"Валек", :city_id=>3621, :sirena_name=>"original", :morpher_to=>"во Валек", :morpher_from=>"из Валека", :morpher_in=>"во Валеке", :lat=>88.220481, :lng=>69.330406})
Airport.create({:iata=>"NSK", :iata_ru=>"НАК", :name_en=>"Alykell", :name_ru=>"Норильск Алыкель", :city_id=>3621, :sirena_name=>"original", :morpher_to=>"в Норильск Алыкель", :morpher_from=>"из Норильск Алыкели", :morpher_in=>"в Норильск Алыкели", :lat=>88.220481, :lng=>69.330406})
Airport.create({:iata=>"ОДЕ", :iata_ru=>"ОДЕ", :name_en=>"Zastava", :name_ru=>"Застава", :city_id=>2102, :sirena_name=>"original", :morpher_to=>"в Заставу", :morpher_from=>"из Заставы", :morpher_in=>"в Заставе", :lat=>30.65359, :lng=>46.478603})
Airport.create({:iata=>"UCА", :iata_ru=>"УЧА", :name_en=>"Ucebnyj", :name_ru=>"Учебный", :city_id=>3622, :sirena_name=>"original", :morpher_to=>"в Учебный", :morpher_from=>"из Учебного", :morpher_in=>"в Учебного", :lat=>95.692982, :lng=>56.219552})
Airport.create({:iata=>"ULY", :iata_ru=>"УЛС", :name_en=>"Vostochniy", :name_ru=>"Восточный", :city_id=>3623, :sirena_name=>"original", :morpher_to=>"во Восточный", :morpher_from=>"из Восточного", :morpher_in=>"во Восточного", :lat=>48.472015, :lng=>54.316581})
Airport.create({:iata=>"УЛК", :iata_ru=>"УЛК", :name_en=>"Ylianovsk", :name_ru=>"Ульяновск", :city_id=>3623, :sirena_name=>"original", :morpher_to=>"в Ульяновск", :morpher_from=>"из Ульяновска", :morpher_in=>"в Ульяновске", :lat=>48.472015, :lng=>54.316581})
Airport.create({:iata=>"БРС", :iata_ru=>"БРС", :name_en=>"Братск", :name_ru=>"Братск", :city_id=>400, :sirena_name=>"original", :morpher_to=>"в Братск", :morpher_from=>"из Братска", :morpher_in=>"в Братске", :lat=>101.591634, :lng=>56.169659})
Airport.create({:iata=>"КЗД", :iata_ru=>"КЗД", :name_en=>"Iudino", :name_ru=>"Юдино", :city_id=>1041, :sirena_name=>"original", :morpher_to=>"в Юдино", :morpher_from=>"из Юдино", :morpher_in=>"в Юдино", :lat=>48.895579, :lng=>55.820329})
Airport.create({:iata=>"КЗЙ", :iata_ru=>"КЗЙ", :name_en=>"Борисоглебское", :name_ru=>"Борисоглебское", :city_id=>1041, :sirena_name=>"original", :morpher_to=>"в Борисоглебское", :morpher_from=>"из Борисоглебское", :morpher_in=>"в Борисоглебское", :lat=>49.147126, :lng=>55.873481})
Airport.create({:iata=>"КЗЬ", :iata_ru=>"КЗЬ", :name_en=>"Cazan 2", :name_ru=>"Казань 2", :city_id=>1041, :sirena_name=>"original", :morpher_to=>"в Казань 2", :morpher_from=>"из Казань 2а", :morpher_in=>"в Казань 2е", :lat=>49.122853, :lng=>55.786764})
Airport.create({:iata=>"DNP", :iata_ru=>"ДНП", :name_en=>"Podgorodnoe", :name_ru=>"Подгородное", :city_id=>873, :sirena_name=>"original", :morpher_to=>"в Подгородное", :morpher_from=>"из Подгородное", :morpher_in=>"в Подгородное", :lat=>35.097834, :lng=>48.57491})
Airport.create({:iata=>"DPC", :iata_ru=>"ДПК", :name_en=>"Dnерrоретrоvsс", :name_ru=>"Днепропетровск", :city_id=>873, :sirena_name=>"original", :morpher_to=>"в Днепропетровск", :morpher_from=>"из Днепропетровска", :morpher_in=>"в Днепропетровске", :lat=>35.045408, :lng=>48.464567})
Airport.create({:iata=>"ZRB", :iata_ru=>"ЗРБ", :name_en=>"Irebuni", :name_ru=>"Эребуни", :city_id=>927, :sirena_name=>"original", :morpher_to=>"в Эребуни", :morpher_from=>"из Эребуни", :morpher_in=>"в Эребуни", :lat=>44.506007, :lng=>40.15816})
Airport.create({:iata=>"ЭРБ", :iata_ru=>"ЭРБ", :name_en=>"Eribuni", :name_ru=>"Эрибуни", :city_id=>927, :sirena_name=>"original", :morpher_to=>"в Эрибуни", :morpher_from=>"из Эрибуни", :morpher_in=>"в Эрибуни", :lat=>44.506007, :lng=>40.15816})
Airport.create({:iata=>"ЗВР", :iata_ru=>"ЗВР", :name_en=>"Zvartnots", :name_ru=>"Звартноц", :city_id=>927, :sirena_name=>"original", :morpher_to=>"в Звартноц", :morpher_from=>"из Звартноца", :morpher_in=>"в Звартноце", :lat=>44.506007, :lng=>40.15816})
Airport.create({:iata=>"ЕКГ", :iata_ru=>"ЕКГ", :name_en=>"Aramil", :name_ru=>"Арамиль", :city_id=>926, :sirena_name=>"original", :morpher_to=>"в Арамиль", :morpher_from=>"из Арамили", :morpher_in=>"в Арамили", :lat=>60.840586, :lng=>56.700034})
Airport.create({:iata=>"УКС", :iata_ru=>"УКС", :name_en=>"Уktуc", :name_ru=>"Уктус", :city_id=>926, :sirena_name=>"original", :morpher_to=>"в Уктус", :morpher_from=>"из Уктуса", :morpher_in=>"в Уктусе", :lat=>60.62517, :lng=>56.777908})
Airport.create({:iata=>"КЯС", :iata_ru=>"КЯС", :name_en=>"Cheremshanka", :name_ru=>"Черемшанка", :city_id=>1347, :sirena_name=>"original", :morpher_to=>"в Черемшанку", :morpher_from=>"из Черемшанкы", :morpher_in=>"в Черемшанке", :lat=>92.534397, :lng=>56.175802})
Airport.create({:iata=>"ЭНЕ", :iata_ru=>"ЭНЕ", :name_en=>"Inem", :name_ru=>"Энем", :city_id=>1346, :sirena_name=>"original", :morpher_to=>"в Энем", :morpher_from=>"из Энема", :morpher_in=>"в Энеме", :lat=>38.976032, :lng=>45.034942})
Airport.create({:iata=>"КУИ", :iata_ru=>"КУИ", :name_en=>"Cutaisi 2", :name_ru=>"Кутаиси2", :city_id=>3624, :sirena_name=>"original", :morpher_to=>"в Кутаиси2", :morpher_from=>"из Кутаиси2а", :morpher_in=>"в Кутаиси2е", :lat=>42.692434, :lng=>42.233128})
Airport.create({:iata=>"CIS", :iata_ru=>"КИС", :name_en=>"Cutaisi", :name_ru=>"Кутаиси", :city_id=>3624, :sirena_name=>"original", :morpher_to=>"в Кутаиси", :morpher_from=>"из Кутаиси", :morpher_in=>"в Кутаиси", :lat=>42.692434, :lng=>42.233128})
Airport.create({:iata=>"КИУ", :iata_ru=>"КИУ", :name_en=>"Copitnary", :name_ru=>"Кутаиси Копитнари", :city_id=>3624, :sirena_name=>"original", :morpher_to=>"в Кутаиси Копитнари", :morpher_from=>"из Кутаиси Копитнари", :morpher_in=>"в Кутаиси Копитнари", :lat=>42.692434, :lng=>42.233128})
Airport.create({:iata=>"СМЫ", :iata_ru=>"СМЫ", :name_en=>"Smichliaevca", :name_ru=>"Смышляевка", :city_id=>2563, :sirena_name=>"original", :morpher_to=>"в Смышляевку", :morpher_from=>"из Смышляевкы", :morpher_in=>"в Смышляевке", :lat=>50.392388, :lng=>53.243427})
Airport.create({:iata=>"СБЫ", :iata_ru=>"СБЫ", :name_en=>"Bezimjnca", :name_ru=>"Безымянка", :city_id=>2563, :sirena_name=>"original", :morpher_to=>"в Безымянку", :morpher_from=>"из Безымянкы", :morpher_in=>"в Безымянке", :lat=>50.248891, :lng=>53.212997})
Airport.create({:iata=>"МГД", :iata_ru=>"МГД", :name_en=>"Magadan 13", :name_ru=>"Магадан 13", :city_id=>1635, :sirena_name=>"original", :morpher_to=>"в Магадан 13", :morpher_from=>"из Магадан 13а", :morpher_in=>"в Магадан 13е", :lat=>150.813078, :lng=>59.55632})
Airport.create({:iata=>"МДС", :iata_ru=>"МДС", :name_en=>"Magadan Sokol", :name_ru=>"Магадан Сокол", :city_id=>1635, :sirena_name=>"original", :morpher_to=>"в Магадан Сокол", :morpher_from=>"из Магадан Сокола", :morpher_in=>"в Магадан Соколе", :lat=>150.813078, :lng=>59.55632})
Airport.create({:iata=>"ТВП", :iata_ru=>"ТВП", :name_en=>"Plechanovo Vostochniy", :name_ru=>"Плеханово Восточный", :city_id=>3089, :sirena_name=>"original", :morpher_to=>"в Плеханово Восточный", :morpher_from=>"из Плеханово Восточного", :morpher_in=>"в Плеханово Восточного", :lat=>65.558412, :lng=>57.182631})
Airport.create({:iata=>"ПЛХ", :iata_ru=>"ПЛХ", :name_en=>"Plechanovo", :name_ru=>"Плеханово", :city_id=>3089, :sirena_name=>"original", :morpher_to=>"в Плеханово", :morpher_from=>"из Плеханово", :morpher_in=>"в Плеханово", :lat=>65.448539, :lng=>57.139483})
Airport.create({:iata=>"МПХ", :iata_ru=>"МПХ", :name_en=>"Xanskaja", :name_ru=>"Ханская", :city_id=>3625, :sirena_name=>"original", :morpher_to=>"в Ханскаю", :morpher_from=>"из Ханскаи", :morpher_in=>"в Ханскаи", :lat=>40.102348, :lng=>44.609539})
Airport.create({:iata=>"МКП", :iata_ru=>"МКП", :name_en=>"Majkop", :name_ru=>"Майкоп", :city_id=>3625, :sirena_name=>"original", :morpher_to=>"в Майкоп", :morpher_from=>"из Майкопа", :morpher_in=>"в Майкопе", :lat=>40.102348, :lng=>44.609539})
Airport.create({:iata=>"THC", :iata_ru=>"ТШК", :name_en=>"Sergeli", :name_ru=>"Сергели", :city_id=>2952, :sirena_name=>"original", :morpher_to=>"в Сергели", :morpher_from=>"из Сергели", :morpher_in=>"в Сергели", :lat=>69.260674, :lng=>41.258054})
Airport.create({:iata=>"ТРЛ", :iata_ru=>"ТРЛ", :name_en=>"Tura  Mvl", :name_ru=>"Тура Мвл", :city_id=>3626, :sirena_name=>"original", :morpher_to=>"в Тура Мвл", :morpher_from=>"из Тура Мвла", :morpher_in=>"в Тура Мвле", :lat=>52.42939, :lng=>57.679016})
Airport.create({:iata=>"ТАУ", :iata_ru=>"ТАУ", :name_en=>"Tura", :name_ru=>"Тура", :city_id=>3626, :sirena_name=>"original", :morpher_to=>"в Туру", :morpher_from=>"из Туры", :morpher_in=>"в Туре", :lat=>100.232636, :lng=>64.27867})
Airport.create({:iata=>"СМФ", :iata_ru=>"СМФ", :name_en=>"Zavodscoe", :name_ru=>"Заводское", :city_id=>2765, :sirena_name=>"original", :morpher_to=>"в Заводское", :morpher_from=>"из Заводское", :morpher_in=>"в Заводское", :lat=>34.067888, :lng=>44.918585})
Airport.create({:iata=>"KAY", :iata_ru=>"КАЫ", :name_en=>"Karym", :name_ru=>"Карым", :city_id=>3627, :sirena_name=>"original", :morpher_to=>"в Карым", :morpher_from=>"из Карыма", :morpher_in=>"в Карыме", :lat=>66.610087, :lng=>60.077638})
Airport.create({:iata=>"УФМ", :iata_ru=>"УФМ", :name_en=>"Macsimovca", :name_ru=>"Максимовка", :city_id=>3147, :sirena_name=>"original", :morpher_to=>"в Максимовку", :morpher_from=>"из Максимовкы", :morpher_in=>"в Максимовке", :lat=>55.983161, :lng=>54.738437})
Airport["MSQ"].update_attributes({:iata_ru=>"МИК", :sirena_name=>"Минск 2"})
Airport["MHP"].update_attributes({:iata_ru=>"МСЛ", :sirena_name=>"Минск 1"})
Airport["OMS"].update_attributes({:iata_ru=>"ОМС"})
Airport["KHV"].update_attributes({:iata_ru=>"ХБР", :sirena_name=>"Хабаровск"})
Airport["VKO"].update_attributes({:iata_ru=>"ВНК"})
Airport["DME"].update_attributes({:iata_ru=>"ДМД"})
Airport["SVO"].update_attributes({:iata_ru=>"ШРМ"})
Airport["LED"].update_attributes({:iata_ru=>"ПЛК"})
Airport["LHR"].update_attributes({:iata_ru=>"LHR"})
Airport["LGW"].update_attributes({:iata_ru=>"LGW", :sirena_name=>"Гатвик"})
Airport["ARN"].update_attributes({:iata_ru=>"ARN", :sirena_name=>"Arlanda"})
Airport["TXL"].update_attributes({:iata_ru=>"TXL"})
Airport["SXF"].update_attributes({:iata_ru=>"SXF", :sirena_name=>"Шенефельд"})
Airport["ORD"].update_attributes({:iata_ru=>"ORD", :sirena_name=>"Орландо"})
Airport["KBP"].update_attributes({:iata_ru=>"БСП"})
Airport["IEV"].update_attributes({:iata_ru=>"ЖУЛ", :sirena_name=>"Жуляны"})
Airport["OVB"].update_attributes({:iata_ru=>"ТЛЧ"})
Airport["DYR"].update_attributes({:iata_ru=>"АНЫ"})
Airport["PKC"].update_attributes({:iata_ru=>"ПРЛ", :sirena_name=>"Елизово"})
Airport["GYD"].update_attributes({:iata_ru=>"БАК", :sirena_name=>"Ап Баку Гейдар Алиев"})
Airport["ALA"].update_attributes({:iata_ru=>"АЛА", :sirena_name=>"Алмааты"})
Airport["JFK"].update_attributes({:iata_ru=>"JFK", :sirena_name=>"Кеннеди"})
Airport["VIN"].update_attributes({:iata_ru=>"ВИН"})
Airport["ODS"].update_attributes({:iata_ru=>"ОДС", :sirena_name=>"Одесса"})
Airport["KZN"].update_attributes({:iata_ru=>"ККЗ", :sirena_name=>"Казань Основной"})
Airport["SVX"].update_attributes({:iata_ru=>"КЛЦ"})
Airport["KJA"].update_attributes({:iata_ru=>"ЕМВ", :sirena_name=>"Емельяново"})
Airport["KRR"].update_attributes({:iata_ru=>"КПА", :sirena_name=>"Краснодар Пашковская"})
Airport["KUF"].update_attributes({:iata_ru=>"СКЧ"})
Airport["TJM"].update_attributes({:iata_ru=>"РЩН", :sirena_name=>"Тюмень Рощино"})
Airport["TAS"].update_attributes({:iata_ru=>"ТАС", :sirena_name=>"Ташкент"})
Airport["SIP"].update_attributes({:iata_ru=>"СИП"})
Airport["FRA"].update_attributes({:iata_ru=>"ФРА", :sirena_name=>"Франкфурт Международный"})
Airport["MUC"].update_attributes({:iata_ru=>"MUC", :sirena_name=>"Франц Жозеф Штраусс"})
Airport["UFA"].update_attributes({:iata_ru=>"УФА"})
Airport["MXP"].update_attributes({:iata_ru=>"MXP"})
Airport["LIN"].update_attributes({:iata_ru=>"LIN", :sirena_name=>"Linate"})
Airport["PMF"].update_attributes({:iata_ru=>"PMF"})
Airport["BGY"].update_attributes({:iata_ru=>"BGY", :sirena_name=>"Orio Al Serio"})
Airport["SWK"].update_attributes({:iata_ru=>"SWK", :sirena_name=>"Segrate"})
Airport["CDG"].update_attributes({:iata_ru=>"ЦДГ", :sirena_name=>"Шарль Де Голь"})
Airport["TSF"].update_attributes({:iata_ru=>"TSF", :sirena_name=>"Treviso"})
